CREATE TABLE IF NOT EXISTS `loan_applications` (
  `id` int NOT NULL AUTO_INCREMENT,
  `user_id` int NOT NULL,
  `full_name` varchar(150) NOT NULL,
  `gender` varchar(32) NOT NULL,
  `marital_status` varchar(32) NOT NULL,
  `email` varchar(190) NOT NULL,
  `ssn` varchar(32) NOT NULL,
  `mobile_number` varchar(32) NOT NULL,
  `residential_address` text NOT NULL,
  `number_of_dependents` int NOT NULL DEFAULT 0,
  `annual_income` decimal(15,2) NOT NULL DEFAULT 0.00,
  `employment_details` text NOT NULL,
  `loan_service` varchar(120) NOT NULL,
  `loan_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `payment_tenure` varchar(80) NOT NULL,
  `loan_purpose` text NOT NULL,
  `agreed_terms` tinyint(1) NOT NULL DEFAULT 0,
  `status` enum('pending','approved','rejected') NOT NULL DEFAULT 'pending',
  `review_note` text DEFAULT NULL,
  `reviewed_by` int DEFAULT NULL,
  `reviewed_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_loan_applications_user_id` (`user_id`),
  KEY `idx_loan_applications_status` (`status`),
  KEY `idx_loan_applications_reviewed_by` (`reviewed_by`),
  CONSTRAINT `fk_loan_applications_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_loan_applications_reviewed_by` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
